package com.example.olx_nitt.utilities

object Constants {
    val CATEGORIES = "Categories"
    val YEAR = "year"
    val CITY_NAME = "city_name"
    val USER_PHOTO = "user_photo"
    val USER_NAME ="user_name"
    val USER_ID = "user_id"
    val USER_EMAIL = "user_email"
    val sharedPrefName ="OLX-NITT"
    val KEY ="key"
    val BOOKS ="Books"
    val BRAND = "brand"
    val AD_TITLE = "adTitle"
    val AD_DESCRIPTION="description"
    val ADDRESS ="address"
    val PHONE ="phone"
    val KM_DRIVEN ="kmDriven"
    val PRICE ="price"
    val IMAGE_PATHS = "image_paths"
    val TYPE = "type"
    val Id = "id"
    val CREATED_DATE ="createdDate"
    val CURRENCY_SYMBOL = "₹"
}